/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rizky.database.mainform;


import com.rizky.database.client.form.Form;
import com.rizky.databaseapi.entity.service.PersonService;
import com.rizky.databaseserver.utilities.DatabaseUtilities;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Muhamad Rizky
 */
public class MainForm extends javax.swing.JFrame {

    static Connection con;
    static ResultSet rs;
    static PreparedStatement ps;
    static Statement stm;
    /**
     * Creates new form MainForm
     */
    public MainForm(){
        initComponents();
        con = DatabaseUtilities.getConnection();
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textMatkul = new javax.swing.JComboBox<>();
        buttonIsiNilai = new javax.swing.JButton();
        textNamaDosen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("Dosen");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Penilaian Akademik");

        jLabel3.setText("Dosen");

        textMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Mata Kuliah :" }));
        textMatkul.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                textMatkulPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        textMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMatkulActionPerformed(evt);
            }
        });

        buttonIsiNilai.setText("Isi Nilai");
        buttonIsiNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIsiNilaiActionPerformed(evt);
            }
        });

        textNamaDosen.setEditable(false);

        jLabel5.setText("Kelas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonIsiNilai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textMatkul, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNamaDosen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatkul, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNamaDosen)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addComponent(buttonIsiNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(158, 158, 158))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fillComboBox(){
        String qry = "SELECT * FROM dosen";
        try {
            ps=con.prepareStatement(qry);
            rs=ps.executeQuery();
            while (rs.next()) {
                textMatkul.addItem(rs.getString("mataKuliah"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void isiNilai() throws RemoteException, NotBoundException{
        Registry registry = LocateRegistry.getRegistry("localhost", 6789);
        PersonService service = (PersonService) registry.lookup("service");
        Object textNamaMatkul = textMatkul.getSelectedItem().toString();
        Object textDosen = textNamaDosen.getText();
        String tm = textMatkul.getSelectedItem().toString();
        
        if (tm.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih Kelas Dahulu!!!");
        }
        if (textMatkul.getSelectedIndex() == 0) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    Form form = new Form(service, (String)textNamaMatkul);
                    form.getLabelMataKuliah().setText((String) textNamaMatkul);
                    form.getLabelNamaDosen().setText((String) textDosen);
                    form.setVisible(true);
                }
            });
        } else {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    Form form = new Form(service, (String)textNamaMatkul);
                    form.getLabelMataKuliah().setText((String) textNamaMatkul);
                    form.getLabelNamaDosen().setText((String) textDosen);
                    form.setVisible(true);
                }
            });
        }
        this.setVisible(false);   
    }

    public void setTextMatkul(JComboBox<String> textMatkul) {
        this.textMatkul = textMatkul;
    }

    public JComboBox<String> getTextMatkul() {
        return textMatkul;
    }
    
    private void textMatkulPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_textMatkulPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        SwingUtilities.getRootPane(buttonIsiNilai).setDefaultButton(buttonIsiNilai);
        String tmp = (String)textMatkul.getSelectedItem();
        String qry = "SELECT * FROM dosen WHERE mataKuliah ='"+tmp+"'";
        try {
            ps=con.prepareStatement(qry);
            rs=ps.executeQuery();
            if (rs.next()) {
                String dosen = rs.getString("namaDosen");
                textNamaDosen.setText(dosen);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textMatkulPopupMenuWillBecomeInvisible

    private void buttonIsiNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIsiNilaiActionPerformed
        try {
            isiNilai();
        } catch (RemoteException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonIsiNilaiActionPerformed

    private void textMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatkulActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIsiNilai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> textMatkul;
    private javax.swing.JTextField textNamaDosen;
    // End of variables declaration//GEN-END:variables
}
