/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rizky.database.client.form;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.VerticalPositionMark;
import com.rizky.database.client.model.tabelModelPerson;
import com.rizky.database.mainform.MainForm;
import com.rizky.databaseapi.entity.Person;
import com.rizky.databaseapi.entity.service.PersonService;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.List;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Muhamad Rizky
 */
public class Form extends javax.swing.JFrame {
    
    private tabelModelPerson tabelModelPerson = new tabelModelPerson();
    private PersonService personService;
    
    /**
     * Creates new form Form
     */
    public Form(PersonService personService, String tmp) {
        
        this.personService = personService;
        
        try {
            tabelModelPerson.setData(this.personService.getPerson(tmp));
        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
        initComponents();
        tablePerson.setModel(tabelModelPerson);
        tablePerson.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
           
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = tablePerson.getSelectedRow();
                if(row != -1){
                    Person person = tabelModelPerson.get(row);
                    textIdPerson.setValue(person.getIdPerson());
                    textFirstName.setText(person.getFirstName());
                    textJenisKelamin.setSelectedItem(person.getJenisKelamin());
                    textBirthday.setValue(person.getBirthday());
                    textNilaiTugas1.setText(person.getNilaiTugas1());
                    textNilaiTugas2.setText(person.getNilaiTugas2());
                    textNilaiUTS.setText(person.getNilaiUTS());
                    textNilaiUAS.setText(person.getNilaiUAS());
                    textNilaiAkhir.setText(person.getNilaiAkhir());
                    textGrade.setText(person.getGrade());
                    labelMataKuliah.setText(person.getMataKuliah());
                }
            }
        });
    }
    public JLabel getLabelMataKuliah() {
        return labelMataKuliah;
    }

    public JLabel getLabelNamaDosen() {
        return labelNamaDosen;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePerson = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textIdPerson = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        textFirstName = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        textBirthday = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNilaiTugas2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        textNilaiUTS = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        textNilaiUAS = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textNilaiAkhir = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        textGrade = new javax.swing.JFormattedTextField();
        buttonClear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        textNilaiTugas1 = new javax.swing.JFormattedTextField();
        buttonInsert = new javax.swing.JButton();
        textJenisKelamin = new javax.swing.JComboBox<>();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();
        labelMataKuliah = new javax.swing.JLabel();
        labelNamaDosen = new javax.swing.JLabel();
        buttonPrint = new javax.swing.JButton();
        textKelas = new javax.swing.JLabel();
        textDosen = new javax.swing.JLabel();
        textNA = new javax.swing.JLabel();
        textSemester = new javax.swing.JLabel();
        textAlamat1 = new javax.swing.JLabel();
        textAlamat2 = new javax.swing.JLabel();
        textAlamat3 = new javax.swing.JLabel();
        textAlamat4 = new javax.swing.JLabel();
        textAlamat5 = new javax.swing.JLabel();
        jLogo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPicture = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Menghitung Nilai Akhir Mahasiswa Dengan Grade");
        setBackground(new java.awt.Color(0, 255, 102));

        tablePerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jenis Kelamin", "Tanggal Lahir", "Tugas 1", "Tugas 2", "UTS", "UAS", "Nilai Akhir", "Grade", "Mata Kuliah"
            }
        ));
        jScrollPane1.setViewportView(tablePerson);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Person"));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("NIM");

        textIdPerson.setEditable(false);
        textIdPerson.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textIdPerson.setValue(new Long(0L));
        textIdPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdPersonActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        textFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFirstNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Tanggal Lahir");

        textBirthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MMMM yyyy"))));
        textBirthday.setValue(new java.util.Date());
        textBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBirthdayActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kelamin");

        jLabel5.setText("Tugas 2");

        textNilaiTugas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNilaiTugas2ActionPerformed(evt);
            }
        });

        jLabel6.setText("UTS");

        textNilaiUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNilaiUTSActionPerformed(evt);
            }
        });

        jLabel7.setText("UAS");

        textNilaiUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNilaiUASActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Content"));

        jLabel8.setText("Nilai Akhir");

        textNilaiAkhir.setEditable(false);
        textNilaiAkhir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textNilaiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNilaiAkhirActionPerformed(evt);
            }
        });

        jLabel9.setText("Grade");

        textGrade.setEditable(false);
        textGrade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textGradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNilaiAkhir)
                    .addComponent(textGrade))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNilaiAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        jLabel10.setText("Tugas 1");

        textNilaiTugas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNilaiTugas1ActionPerformed(evt);
            }
        });

        buttonInsert.setText("Save");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });

        textJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
        textJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJenisKelaminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textIdPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(textBirthday)
                                .addComponent(textFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(textJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNilaiUAS, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(textNilaiTugas1)
                            .addComponent(textNilaiTugas2)
                            .addComponent(textNilaiUTS))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(buttonInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textIdPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNilaiTugas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(textNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textNilaiTugas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonInsert)
                            .addComponent(buttonClear))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        labelMataKuliah.setText("Kelas");

        labelNamaDosen.setText("Nama Dosen");

        buttonPrint.setText("Print");
        buttonPrint.setToolTipText("");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        textKelas.setText("Kelas      :");

        textDosen.setText("Dosen        :     ");

        textNA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textNA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textNA.setText("Nilai Akhir");

        textSemester.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSemester.setText("Semester Genap 2017 - 2018");

        textAlamat1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textAlamat1.setText("UNIVERSITAS ESA UNGGUL");

        textAlamat2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textAlamat2.setText("FAKULTAS ILMU KOMPUTER");

        textAlamat3.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        textAlamat3.setText("Jalan Arjuna Utara No.9, Kebon Jeruk - Jakarta Barat 11510");

        textAlamat4.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        textAlamat4.setText("021 - 5674223 (hunting) 021- 5682510 (direct) Fax : 021 - 5674248");

        textAlamat5.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        textAlamat5.setText("Website: www.esaunggul.ac.id, email: info@esaunggul.ac.id");

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rizky/database/client/form/Uesaunggul.png"))); // NOI18N
        jPicture.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAlamat2)
                            .addComponent(textAlamat1)
                            .addComponent(textAlamat3)
                            .addComponent(textAlamat4)
                            .addComponent(textAlamat5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonKembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonRefresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(textKelas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelMataKuliah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textDosen)
                                .addGap(18, 18, 18)
                                .addComponent(labelNamaDosen))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 351, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textSemester, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(textNA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 344, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textAlamat1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAlamat2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAlamat3)
                                .addGap(5, 5, 5)
                                .addComponent(textAlamat4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAlamat5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSemester)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKelas)
                    .addComponent(labelMataKuliah)
                    .addComponent(textDosen)
                    .addComponent(labelNamaDosen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPrint))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        try {
            List<Person> list = personService.getPerson(labelMataKuliah.getText());
            tabelModelPerson.setData(list);
        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
    }//GEN-LAST:event_buttonRefreshActionPerformed
    
    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        double nTugas1, nTugas2, nUTS, nUAS, nAkhir;
        String tugas1 = textNilaiTugas1.getText();
        String tugas2 = textNilaiTugas2.getText();
        String UTS = textNilaiUTS.getText();
        String UAS = textNilaiUAS.getText();
        String hasil;
        
        if(tugas1.isEmpty() || tugas2.isEmpty() || UTS.isEmpty() || UAS.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nilai Tidak Boleh Kosong!");
        }
        else {
            try {
                int row = tablePerson.getSelectedRow();
                if(row == -1){
                    return;
                }
                nTugas1 = Float.parseFloat(textNilaiTugas1.getText());
                nTugas2 = Float.parseFloat(textNilaiTugas2.getText());
                nUTS = Float.parseFloat(textNilaiUTS.getText());
                nUAS = Float.parseFloat(textNilaiUAS.getText());
                nAkhir = (nTugas1*0.2)+(nTugas2*0.3)+(nUTS*0.2)+(nUAS*0.3);
                hasil=String.valueOf(nAkhir);
                textNilaiAkhir.setText(hasil);

                if (nAkhir >=80 && nAkhir <=100) {
                    textGrade.setText("A");
                }
                else if (nAkhir >=70 && nAkhir <80) {
                    textGrade.setText("B");
                }
                else if (nAkhir >= 60 && nAkhir <70) {
                    textGrade.setText("C");
                }
                else if (nAkhir >= 50 && nAkhir <60) {
                    textGrade.setText("D");
                }
                else
                textGrade.setText("E");
            
                Person person = tabelModelPerson.get(row);
                person.setFirstName(textFirstName.getText());
                person.setJenisKelamin((String)textJenisKelamin.getSelectedItem());
                person.setBirthday((Date)textBirthday.getValue());
                person.setNilaiTugas1(textNilaiTugas1.getText());
                person.setNilaiTugas2(textNilaiTugas2.getText());
                person.setNilaiUTS(textNilaiUTS.getText());
                person.setNilaiUAS(textNilaiUAS.getText());
                person.setNilaiAkhir(textNilaiAkhir.getText());
                person.setGrade(textGrade.getText());

                personService.updatePerson(person);
                tabelModelPerson.update(row, person);
            } catch (RemoteException exception) {
                exception.printStackTrace();
            }
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        try {
            int row = tablePerson.getSelectedRow();
            if (row == -1) {
                return;
            }
            Long idPerson = tabelModelPerson.get(row).getIdPerson();
            personService.deletePerson(idPerson);
            tabelModelPerson.delete(row);
        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        double nTugas1, nTugas2, nUTS, nUAS, nAkhir;
        String tugas1 = textNilaiTugas1.getText();
        String tugas2 = textNilaiTugas2.getText();
        String UTS = textNilaiUTS.getText();
        String UAS = textNilaiUAS.getText();
        String hasil;

        if(tugas1.isEmpty() || tugas2.isEmpty() || UTS.isEmpty() || UAS.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nilai Tidak Boleh Kosong!");
        }
        else {
            nTugas1 = Float.parseFloat(textNilaiTugas1.getText());
            nTugas2 = Float.parseFloat(textNilaiTugas2.getText());
            nUTS = Float.parseFloat(textNilaiUTS.getText());
            nUAS = Float.parseFloat(textNilaiUAS.getText());
            nAkhir = (nTugas1*0.2)+(nTugas2*0.3)+(nUTS*0.2)+(nUAS*0.3);
            hasil=String.valueOf(nAkhir);
            textNilaiAkhir.setText(hasil);
            if (nAkhir >=80 && nAkhir <=100) {
                textGrade.setText("A");
            }
            else if (nAkhir >=70 && nAkhir <80) {
                textGrade.setText("B");
            }
            else if (nAkhir >= 60 && nAkhir <70) {
                textGrade.setText("C");
            }
            else if (nAkhir >= 50 && nAkhir <60) {
                textGrade.setText("D");
            }
            else
            textGrade.setText("E");
        
            try {
                Person person = new Person();
                person.setFirstName(textFirstName.getText());
                person.setJenisKelamin((String)textJenisKelamin.getSelectedItem());
                person.setBirthday((Date)textBirthday.getValue());
                person.setNilaiTugas1(textNilaiTugas1.getText());
                person.setNilaiTugas2(textNilaiTugas2.getText());
                person.setNilaiUTS(textNilaiUTS.getText());
                person.setNilaiUAS(textNilaiUAS.getText());
                person.setNilaiAkhir(textNilaiAkhir.getText());
                person.setGrade(textGrade.getText());
                person.setMataKuliah(labelMataKuliah.getText());
                        
                Person person1 = personService.insertPerson(person);
                tabelModelPerson.insert(person1);

            } catch (RemoteException exception) {
                exception.printStackTrace();
            }
        }
    }//GEN-LAST:event_buttonInsertActionPerformed

    
    private void textNilaiTugas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNilaiTugas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiTugas1ActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        textFirstName.setText("");
        textNilaiTugas1.setText("");
        textNilaiTugas2.setText("");
        textNilaiUTS.setText("");
        textNilaiUAS.setText("");
        textNilaiAkhir.setText("");
        textGrade.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed
    
    private void textGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textGradeActionPerformed

    private void textNilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNilaiAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiAkhirActionPerformed

    private void textNilaiUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNilaiUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiUASActionPerformed

    private void textNilaiUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNilaiUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiUTSActionPerformed

    private void textNilaiTugas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNilaiTugas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiTugas2ActionPerformed

    private void textBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBirthdayActionPerformed

    private void textFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFirstNameActionPerformed

    private void textIdPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdPersonActionPerformed

    private void textJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJenisKelaminActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        String path = "";
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = jfc.showSaveDialog(this);
        
        if (x==JFileChooser.APPROVE_OPTION) {
            path = jfc.getSelectedFile().getPath();
        }
        Document doc =  new Document(PageSize.A4);
        try {
            String label = labelMataKuliah.getText();
            
            PdfWriter.getInstance(doc, new FileOutputStream(path+"Report "+label+".pdf"));
            doc.open();

            Paragraph p = new Paragraph(textAlamat1.getText());
            Paragraph q = new Paragraph("Kelas  : "+labelMataKuliah.getText());
            Paragraph r = new Paragraph("Dosen  : "+labelNamaDosen.getText());
            Chunk glue = new Chunk(new VerticalPositionMark());
            p.add(new Chunk(glue));
            q.add(new Chunk(glue));
            r.add(new Chunk(glue));
            doc.add(p);
            doc.add(q);
            doc.add(r);
            doc.add( Chunk.NEWLINE );
            
            PdfPTable table = new PdfPTable(11);
            table.setWidthPercentage(100);
            table.addCell("NIM");
            table.addCell("Nama");
            table.addCell("Jenis Kelamin");
            table.addCell("Tanggal Lahir");
            table.addCell("Tugas 1");
            table.addCell("Tugas 2");
            table.addCell("UTS");
            table.addCell("UAS");
            table.addCell("Nilai Akhir");
            table.addCell("Grade");
            table.addCell("Mata Kuliah");
            
            for (int i = 0; i < tablePerson.getRowCount(); i++) {
                String nim = tablePerson.getValueAt(i, 0).toString();
                String nama = tablePerson.getValueAt(i, 1).toString();
                String jk = tablePerson.getValueAt(i, 2).toString();
                String tgl = tablePerson.getValueAt(i, 3).toString();
                String tugas1 = tablePerson.getValueAt(i, 4).toString();
                String tugas2 = tablePerson.getValueAt(i, 5).toString();
                String uts = tablePerson.getValueAt(i, 6).toString();
                String uas = tablePerson.getValueAt(i, 7).toString();
                String na = tablePerson.getValueAt(i, 8).toString();
                String grade = tablePerson.getValueAt(i, 9).toString();
                String matkul = tablePerson.getValueAt(i, 10).toString();
                
                table.addCell(nim);
                table.addCell(nama);
                table.addCell(jk);
                table.addCell(tgl);
                table.addCell(tugas1);
                table.addCell(tugas2);
                table.addCell(uts);
                table.addCell(uas);
                table.addCell(na);
                table.addCell(grade);
                table.addCell(matkul);
            }
            doc.add(table);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonInsert;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPicture;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelMataKuliah;
    private javax.swing.JLabel labelNamaDosen;
    private javax.swing.JTable tablePerson;
    private javax.swing.JLabel textAlamat1;
    private javax.swing.JLabel textAlamat2;
    private javax.swing.JLabel textAlamat3;
    private javax.swing.JLabel textAlamat4;
    private javax.swing.JLabel textAlamat5;
    private javax.swing.JFormattedTextField textBirthday;
    private javax.swing.JLabel textDosen;
    private javax.swing.JFormattedTextField textFirstName;
    private javax.swing.JFormattedTextField textGrade;
    private javax.swing.JFormattedTextField textIdPerson;
    private javax.swing.JComboBox<String> textJenisKelamin;
    private javax.swing.JLabel textKelas;
    private javax.swing.JLabel textNA;
    private javax.swing.JFormattedTextField textNilaiAkhir;
    private javax.swing.JFormattedTextField textNilaiTugas1;
    private javax.swing.JFormattedTextField textNilaiTugas2;
    private javax.swing.JFormattedTextField textNilaiUAS;
    private javax.swing.JFormattedTextField textNilaiUTS;
    private javax.swing.JLabel textSemester;
    // End of variables declaration//GEN-END:variables
}
